repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-added-large-files
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
- repo: https://github.com/psf/black
  rev:  23.1.0
  hooks:
  - id: black
    language: system
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    language: system
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    language: system
    files: ^.*.pyi?$
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.0.1
  hooks:
  - id: mypy
    language: system
    entry: mypy .
    pass_filenames: false
