# Generated by Django 4.2 on 2023-05-09 04:59

import common.db.models.fields
from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "created_at",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="作成日"),
                ),
                (
                    "updated_at",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="更新日"),
                ),
                ("id", common.db.models.fields.ULIDField(editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=50, null=True, verbose_name="プロジェクト識別名")),
                (
                    "store_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="stores.storecategory", verbose_name="カテゴリー"
                    ),
                ),
            ],
            options={
                "verbose_name": "プロジェクト",
                "verbose_name_plural": "プロジェクト",
                "db_table": "projects",
            },
        ),
        migrations.CreateModel(
            name="Research",
            fields=[
                (
                    "created_at",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="作成日"),
                ),
                (
                    "updated_at",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="更新日"),
                ),
                ("id", common.db.models.fields.ULIDField(editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=20, null=True, verbose_name="期間識別名")),
                ("start_date", models.DateField(verbose_name="調査開始日")),
                ("end_date", models.DateField(verbose_name="調査終了日")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="researches.project", verbose_name="プロジェクト"
                    ),
                ),
                (
                    "shelf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="stores.shelf", verbose_name="棚割"
                    ),
                ),
            ],
            options={
                "verbose_name": "調査期間",
                "verbose_name_plural": "調査期間",
                "db_table": "researches",
            },
        ),
        migrations.CreateModel(
            name="ProjectCustomerAttr",
            fields=[
                (
                    "created_at",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="作成日"),
                ),
                (
                    "updated_at",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="更新日"),
                ),
                ("id", common.db.models.fields.ULIDField(editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=10, verbose_name="顧客属性名")),
                ("order", models.PositiveSmallIntegerField(verbose_name="表示順序")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="researches.project", verbose_name="プロジェクト"
                    ),
                ),
            ],
            options={
                "verbose_name": "プロジェクト固有顧客属性",
                "verbose_name_plural": "プロジェクト固有顧客属性",
                "db_table": "project_customer_attributes",
            },
        ),
        migrations.AddConstraint(
            model_name="projectcustomerattr",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("project", "name"),
                name="unique_attr_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectcustomerattr",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("project", "order"),
                name="unique_attr_order",
            ),
        ),
    ]
