# Generated by Django 4.2 on 2023-05-09 04:59

import apps.stores.models
import common.db.models.fields
import datetime
from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shelf",
            fields=[
                (
                    "created_at",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="作成日"),
                ),
                (
                    "updated_at",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="更新日"),
                ),
                ("id", common.db.models.fields.ULIDField(editable=False, primary_key=True, serialize=False)),
                ("start_date", models.DateField(verbose_name="適用開始日")),
                (
                    "end_date",
                    models.DateField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999), verbose_name="適用終了日"),
                ),
                ("image", models.FileField(blank=True, null=True, upload_to="", verbose_name="棚画像")),
                ("file", models.FileField(blank=True, null=True, upload_to="", verbose_name="添付ファイル")),
            ],
            options={
                "verbose_name": "棚割",
                "verbose_name_plural": "棚割",
                "db_table": "shelves",
            },
        ),
        migrations.CreateModel(
            name="ShelfArea",
            fields=[
                (
                    "created_at",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="作成日"),
                ),
                (
                    "updated_at",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="更新日"),
                ),
                ("id", common.db.models.fields.ULIDField(editable=False, primary_key=True, serialize=False)),
                ("area_number", models.PositiveSmallIntegerField(verbose_name="エリア番号")),
                (
                    "shelf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="stores.shelf",
                        verbose_name="棚割",
                    ),
                ),
            ],
            options={
                "verbose_name": "エリア",
                "verbose_name_plural": "エリア",
                "db_table": "shelf_areas",
            },
        ),
        migrations.CreateModel(
            name="ShelfProductAlloc",
            fields=[
                (
                    "created_at",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="作成日"),
                ),
                (
                    "updated_at",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="更新日"),
                ),
                ("id", common.db.models.fields.ULIDField(editable=False, primary_key=True, serialize=False)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stores.shelfarea",
                        verbose_name="エリア",
                    ),
                ),
                (
                    "product",
                    apps.stores.models.ProductCodeField(
                        on_delete=django.db.models.deletion.RESTRICT, to="products.product", verbose_name="商品"
                    ),
                ),
                (
                    "shelf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocs",
                        to="stores.shelf",
                        verbose_name="棚割",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品配置",
                "verbose_name_plural": "商品配置",
                "db_table": "shelf_product_allocations",
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "created_at",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="作成日"),
                ),
                (
                    "updated_at",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="更新日"),
                ),
                ("id", common.db.models.fields.ULIDField(editable=False, primary_key=True, serialize=False)),
                ("name", apps.stores.models.StoreNameField(max_length=30, verbose_name="チェーン名")),
            ],
            options={
                "verbose_name": "店舗",
                "verbose_name_plural": "店舗",
                "db_table": "stores",
            },
        ),
        migrations.CreateModel(
            name="StoreBranch",
            fields=[
                (
                    "created_at",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="作成日"),
                ),
                (
                    "updated_at",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="更新日"),
                ),
                ("id", common.db.models.fields.ULIDField(editable=False, primary_key=True, serialize=False)),
                ("name", apps.stores.models.StoreNameField(max_length=30, verbose_name="支店名")),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="stores.store",
                        verbose_name="店舗",
                    ),
                ),
            ],
            options={
                "verbose_name": "支店",
                "verbose_name_plural": "支店",
                "db_table": "store_branches",
            },
        ),
        migrations.CreateModel(
            name="ShelfAreaRect",
            fields=[
                (
                    "created_at",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="作成日"),
                ),
                (
                    "updated_at",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="更新日"),
                ),
                (
                    "shelf_area",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="stores.shelfarea",
                    ),
                ),
                ("x", models.FloatField(verbose_name="x座標")),
                ("y", models.FloatField(verbose_name="y座標")),
                ("width", models.FloatField(verbose_name="横幅")),
                ("height", models.FloatField(verbose_name="高さ")),
            ],
            options={
                "verbose_name": "エリア矩形",
                "verbose_name_plural": "エリア矩形",
                "db_table": "shelf_area_rects",
            },
        ),
        migrations.CreateModel(
            name="StoreCategory",
            fields=[
                (
                    "created_at",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="作成日"),
                ),
                (
                    "updated_at",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="更新日"),
                ),
                ("id", common.db.models.fields.ULIDField(editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20, verbose_name="カテゴリー名")),
                (
                    "store_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="stores.storebranch",
                        verbose_name="支店",
                    ),
                ),
            ],
            options={
                "verbose_name": "カテゴリー",
                "verbose_name_plural": "カテゴリー",
                "db_table": "store_categories",
            },
        ),
        migrations.CreateModel(
            name="ShelfProductAllocRect",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="作成日"),
                ),
                (
                    "updated_at",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="更新日"),
                ),
                ("x", models.FloatField(verbose_name="x座標")),
                ("y", models.FloatField(verbose_name="y座標")),
                ("width", models.FloatField(verbose_name="矩形幅")),
                ("height", models.FloatField(verbose_name="矩形高")),
                (
                    "alloc_id",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="stores.shelfproductalloc"),
                ),
            ],
            options={
                "verbose_name": "商品配置矩形",
                "verbose_name_plural": "商品配置矩形",
                "db_table": "shelf_product_allocation_rects",
            },
        ),
        migrations.AddField(
            model_name="shelf",
            name="store_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shelves",
                to="stores.storecategory",
                verbose_name="カテゴリー",
            ),
        ),
        migrations.AddConstraint(
            model_name="shelfarea",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("area_number", "shelf"),
                name="unique_area_number",
            ),
        ),
    ]
